name = "ImplicitBVH"
uuid = "932a18dc-bb55-4cd5-bdd6-1368ec9cea29"
authors = ["Andrei Leonard Nicusan <leonard@evophase.co.uk> and contributors"]
version = "0.6.0"

[deps]
AcceleratedKernels = "6a4ca0a5-0e36-4168-a932-d9be78d558f1"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
AcceleratedKernels = "0.4"
ArgCheck = "2"
Atomix = "0.1, 1"
DocStringExtensions = "0.9"
GPUArraysCore = "0.1, 0.2"
KernelAbstractions = "0.9.34"
LinearAlgebra = "1"
julia = "1.10"
