[deps]
AcceleratedKernels = "6a4ca0a5-0e36-4168-a932-d9be78d558f1"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
ImplicitBVH = "932a18dc-bb55-4cd5-bdd6-1368ec9cea29"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"
